version: "3.9"

services:
  fpm:
    build:
      context: .
      dockerfile: deploy/local/fpm/Dockerfile
    volumes:
      - "${PWD}:/www"
  nginx:
    build:
      context: .
      dockerfile: deploy/local/nginx/Dockerfile
    ports:
      - "8123:80"
    depends_on:
      - fpm
  composer:
    build:
      context: .
      dockerfile: deploy/local/composer/Dockerfile
    volumes:
      - "${PWD}:/www"
    entrypoint: ["/bin/bash", "-c"]
    command: ["composer install --no-interaction --optimize-autoloader"]